version: '3.3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    volumes:
      - ../build/var/mqtt/data:/mosquitto/data
      - ../build/var/mqtt/conf:/mosquitto/config
      - ../build/var/mqtt/log:/mosquitto/log
    ports:
      - "18883:1883"
      - "9001:9001"
